name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code for the deployment
      uses: actions/checkout@v2

    - name: SSH into the AWS instance machine and deploy the code there
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      run: |
        echo "$SSH_PRIVATE_KEY" > key_file
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i key_file ubuntu@ec2-51-20-55-68.eu-north-1.compute.amazonaws.com "sudo bash ./deploy.sh" 
